-- CRIAR TABELA DE FUNCIONÁRIOS
CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    CARGO VARCHAR(50) NOT NULL,
    DATA_CONTRATACAO DATE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- CRIAR TABELA DE USUÁRIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    SOBRE_NOME VARCHAR(50) NOT NULL,
    SENHA VARBINARY(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SALDO DECIMAL(10, 2) DEFAULT 0.0,
    TOKEN VARCHAR(255),
    CPF VARCHAR(20),
    FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) 
);

-- CRIAR TABELA DE CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_CONTA VARCHAR(20) UNIQUE NOT NULL,
    TIPO_CONTA VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- CRIAR TABELA DE PRODUTOS
CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10, 2) NOT NULL
);

-- INSERIR UM FUNCIONÁRIO COM O CARGO DE GERENTE
INSERT INTO USUARIOS (NOME_USUARIO, SENHA, PRIMEIRO_NOME, ULTIMO_NOME, EMAIL, SALDO, TOKEN)
VALUES
    ('usuario1', 'senha123', 'João', 'Silva', 'joao.silva@example.com', 100.00, 'token123');





-- CRIAR TABELA DE LOGS
CREATE TABLE LOGS (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_LOG INT,
    TIPO_ATIVIDADE VARCHAR(50) NOT NULL,
    DESCRICAO_ATIVIDADE TEXT,
    HORARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CRIAR TABELA ENDERECO
CREATE TABLE ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);


